#!/bin/bash
GREEN='\033[1;32m'
NC='\033[0m'
function info() {
echo -e "${GREEN}OS:${NC} "$(lsb_release -d | awk '{print $2, $3}')
echo -e "${GREEN}Núcleo:${NC} "$(uname -r) "@ ${GREEN}GCC:${NC} "$(gcc --version | grep "gcc" | awk '{print $4}')
echo -e "${GREEN}CPU:${NC} "$(lscpu | grep 'model' | awk '{print $4, $6, $8, $9}') $(sensors | grep "id" | awk '{print $4}')
echo -e "${GREEN}IGPU:${NC} "$(glxinfo | grep 'Device' | awk '{print $4, $5, $6, $7}')
echo -e "${GREEN}RAM:${NC} "$(free -m | grep "Mem" | awk '{print $3+$5"/"$2" MiB"}')
}
paste <(echo "$(info)")
