#!/bin/sh
GREEN='\033[1;32m'
NC='\033[0m'
function logo(){
echo "                    "
echo "                    "
echo -e "${GREEN}  _____   ______    ${NC}"
echo -e "${GREEN} / ____\\ / ____ \\ ${NC}"
echo -e "${GREEN}/ /    \\/ /    \\ \\ ${NC}"
echo -e "${GREEN}\\ \\____/ /\____/ / ${NC}"
echo -e "${GREEN} \\______/ \\_____/ ${NC}"
echo "                    "
echo "                    "
echo "                    "
}

function informacion(){
echo " "
echo -e "${GREEN}Usuario:${NC} "$(id -un)" -_-"
echo "-------------------------------"
echo -e "${GREEN}Fecha:${NC} "$(date "+%r %x")
echo -e "${GREEN}OS:${NC} "$(lsb-release -d | awk '{print $2, $3}') "@ Snapshot: "$(lsb-release -r | awk '{print $2}')
echo -e "${GREEN}Núcleo:${NC} "$(uname -r) "@ ${GREEN}GCC:${NC} "$(gcc --version | grep "gcc" | awk '{print $4}')
echo -e "${GREEN}CPU:${NC} "$(lscpu | grep 'model' | awk '{print $4, $6, $8, $9}') $(sensors | grep "id" | awk '{print $4}')
echo -e "${GREEN}IGPU:${NC} "$(glxinfo | grep 'Device' | awk '{print $4, $5, $6, $7, $8}')
echo -e "${GREEN}RAM:${NC} "$(free -m | grep "Mem" | awk '{print $3+$5"/"$2" MiB"}')
}

paste <(echo "$(logo)") <(echo "$(informacion)")
echo -e "\t\t\t\t${GREEN}I${NC} love ${GREEN}openSUSE${NC}"
echo " "
